# Generated by Django 4.1.7 on 2023-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "css",
                    models.CharField(
                        default=0, max_length=13, primary_key=True, serialize=False
                    ),
                ),
                ("prenom", models.CharField(max_length=200)),
                ("nom", models.CharField(max_length=200)),
            ],
        ),
    ]
