# Generated by Django 4.2 on 2023-05-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0002_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='css',
        ),
        migrations.AddField(
            model_name='personnel',
            name='civilite',
            field=models.CharField(default='Indéfini', max_length=13, primary_key=True, serialize=False),
        ),
    ]
