# Generated by Django 4.2 on 2023-05-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0003_remove_personnel_css_personnel_civilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='email',
            field=models.CharField(default='default@example.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='poste',
            field=models.CharField(default='employer', max_length=200),
            preserve_default=False,
        ),
    ]
