# Generated by Django 4.2 on 2023-05-10 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0004_personnel_email_personnel_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('PC', 'PC − Run windows '), ('Mac', 'MAc − Run MacOS'), ('Serveur', 'Serveur −Simple Server to deploy virtual machines'), ('Switch', 'Switch − To maintains and connect servers')], default='PC', max_length=32),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 10, 16, 3, 34, 654793)),
        ),
    ]
