# Generated by Django 4.2 on 2023-05-12 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0011_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='id',
            field=models.AutoField(default=None, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 12, 33, 38, 837016)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='civilite',
            field=models.CharField(default='Indéfini', max_length=13),
        ),
    ]
