# Generated by Django 4.2 on 2023-05-18 09:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0012_personnel_id_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='mach',
            new_name='type_machine',
        ),
        migrations.AddField(
            model_name='machine',
            name='lieu_infrastructure',
            field=models.CharField(choices=[('Poitiers', 'Poitiers'), ('Marseille', 'Marseille'), ('Châtellerault', 'Châtellerault')], default='Marseille', max_length=32),
        ),
        migrations.AddField(
            model_name='personnel',
            name='infrastructure',
            field=models.CharField(choices=[('Poitiers', 'Poitiers'), ('Marseille', 'Marseille'), ('Châtellerault', 'Châtellerault')], default='Marseille', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 18, 9, 43, 38, 184835)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.CharField(max_length=50, validators=[django.core.validators.EmailValidator(message='Veuillez entrer une adresse email valide.')]),
        ),
    ]
