# Generated by Django 4.2 on 2023-05-18 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0013_rename_mach_machine_type_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 18, 10, 13, 42, 649701)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('Ingénieur en sécurité informatique', 'Ingénieur en sécurité informatique'), ('Administrateur système', 'Administrateur système'), ('Administrateur réseau', 'Administrateur réseau'), ('Technicien support informatique', 'Technicien support informatique'), ("Analyste en systèmes d'information", "Analyste en systèmes d'information"), ("Développeur d'applications", "Développeur d'applications"), ('Responsable de la gestion des données', 'Responsable de la gestion des données')], default='Employer', max_length=200),
        ),
    ]
