# Generated by Django 4.2 on 2023-05-22 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0014_alter_machine_maintenancedate_alter_personnel_poste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='type_machine',
            new_name='type_materiel',
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 6, 12, 58, 496873)),
        ),
    ]
