# Generated by Django 4.2 on 2023-06-05 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0018_alter_machine_lieu_infrastructure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='nom',
            new_name='nom_m',
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 20, 53, 57, 35966)),
        ),
    ]
