# Generated by Django 4.2 on 2023-06-05 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0019_rename_nom_machine_nom_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 21, 50, 2, 518363)),
        ),
    ]
