# Generated by Django 4.2 on 2023-06-07 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0020_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='off', max_length=3),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 19, 50, 22, 260320)),
        ),
    ]
