# Generated by Django 4.2 on 2023-06-07 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0021_machine_etat_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('on', 'ON'), ('off', 'OFF'), ('maintenance', 'maintenance')], default='off', max_length=12),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 20, 35, 22, 259607)),
        ),
    ]
