# Generated by Django 4.2 on 2023-06-02 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0015_rename_type_machine_machine_type_materiel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 2, 16, 56, 8, 564089)),
        ),
    ]
